project:
  type: website
  post-render: 
    - "cp quarto_listing.js _site/site_libs/quarto-listing/quarto-listing.js"

website:
  navbar:
    search: true
    logo: assets/img/Logo_colib.svg
    left:
      - href: index.qmd
        text: Overview
      - text: About
        menu:
          - text: About Colib
            href: ./about/index.qmd
          - text: Author Guidelines
            href: ./about/authorGuidelines.qmd
          - text: Code of Conduct
            href: ./about/codeConduct.qmd
          - text: Contributing Guidelines
            href: ./about/contribute.qmd
          - text: Notations and conventions
            href: ./about/notationAndConventions.qmd
          - text: Teams and community
            href: ./about/team.qmd
          - text: Terms of Reference
            href: ./about/terms.qmd
      - text: Models
        menu:
          - text: Synchronous Machines
            href: ./models/1-SynchronousMachines/index.qmd
          - text: Loads
            href: ./models/2-Loads/index.qmd
      - text: Test Cases
        menu:
          - text: Grid Following - Grid Forming DC link 
            href: ./testCases/GridFollowing_GridForming_DClink/index.qmd
          - text: Kundur two-area system
            href: ./testCases/kundur_two_area_system/index.qmd
      - href: contribute/index.qmd
        text: Contribute
      - href: contact/index.qmd
        text: Contact
    tools:
      - icon: github
        href: https://github.com/CRESYM/Colib_Quarto.github.io
  sidebar:
    - title: About
      style: floating
      collapse-level: 2
      contents: about
    - title: Models
      style: floating
      collapse-level: 2
      contents: models
    - title: Test Cases
      style: floating
      collapse-level: 2
      contents: testCases
    - title: Contribute
      style: floating
      collapse-level: 2
      contents: contribute
  page-footer:
    left: |
      Copyright © 2023-2025 Authors of Collaborative Open-Source Dynamic Simulation Library. Content licensed under [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/).
    right:
      - text: About
        href: about/index.qmd
      - text: Contact
        href: ./contact.qmd
      - text: Privacy Policy
        href: https://cresym.eu/privacy-policy/
      - text: Terms of Reference
        href: about/terms.qmd
      - icon: github
        href: https://github.com/CRESYM/Colib_Quarto.github.io
    background: light
    border: true
  back-to-top-navigation: true

format:
  html:
    theme:
      - cosmo
    css:
      - styles.css
    toc: true
    grid:
      body-width: 1200px

execute:
  freeze: auto

