project:
  type: website

website:
  title: Colib
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - models.qmd
      - test_cases.qmd
      - templates.qmd
      - contact.qmd

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
