project:
  type: website

website:
  navbar:
    search: true
    logo: assets/img/Logo_colib.svg
    left:
      - href: index.qmd
        text: Overview
      - href: about/index.qmd
        text: About
      - href: models/index.qmd
        text: Models
      - href: test_cases.qmd
        text: Page with code
    tools:
      - icon: github
        href: https://github.com/CRESYM/Colib_Quarto.github.io
  sidebar:
    - title: About
      style: floating
      collapse-level: 2
      contents: about
    - title: Models
      style: floating
      collapse-level: 2
      contents: models
  page-footer:
    left: |
      Copyright © 2023-2025 Authors of Collaborative Open-Source Dynamic Simulation Library.  
      Content licensed under [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/).
    right: |
      [About](about.qmd) • [Contact](contact.qmd) • [Models](models.qmd) • [Test Cases](test_cases.qmd) • [Templates](templates.qmd) • [Privacy Policy](#) • [Terms of Reference](#)
    background: light
    border: true
  back-to-top-navigation: true

format:
  html:
    theme:
      - cosmo
    css:
      - styles.css
    toc: true
    grid:
      body-width: 1200px

execute:
  freeze: auto

