project:
  type: website
  post-render: 
    - "node -e \"require('fs').copyFileSync('javascript/quarto_listing.js', '_site/site_libs/quarto-listing/quarto-listing.js')\""

website:
  favicon: assets/img/Logo_colib.svg
  navbar:
    search: true
    pinned: true
    logo: assets/img/Logo_colib.svg
    left:
      - href: index.qmd
        text: Overview
      - text: About
        menu:
          - text: About Colib
            href: ./about/index.qmd
          - text: Author Guidelines
            href: ./about/authorGuidelines.qmd
          - text: Code of Conduct
            href: ./about/codeConduct.qmd
          - text: Notations and conventions
            href: ./about/notationAndConventions.qmd
          - text: Teams and community
            href: ./about/team.qmd
          - text: Terms of Reference
            href: ./about/terms.qmd
      - text: Models
        menu:
          - text: All models
            href: ./models/index.qmd
          - text: Synchronous Machines
            href: ./models/1-SynchronousMachines/index.qmd
          - text: Loads
            href: ./models/2-Loads/index.qmd
          - text: Compensation and FACTS
            href: ./models/3-CompensationAndFACTS/index.qmd
          - text: HVDC
            href: ./models/4-HVDC/index.qmd
          - text: Renewables and Storage
            href: ./models/5-RenewablesAndStorage/index.qmd
          - text: Network Components
            href: ./models/6-NetworkComponents/index.qmd
          - text: Protection
            href: ./models/7-Protection/index.qmd
          - text: Others
            href: ./models/8-Others/index.qmd
      - text: Test Cases
        menu:
          - text: All test cases
            href: ./testCases/index.qmd
          - text: Grid Following - Grid Forming DC link 
            href: ./testCases/GridFollowing_GridForming_DClink/index.qmd
          - text: Kundur two-area system
            href: ./testCases/kundur_two_area_system/index.qmd
          - text: Converter Driven Stability
            href: ./testCases/converterDrivenStability/index.qmd
          - text: System Frequency Response Model with Underfrequency Load Shedding Protection
            href: ./testCases/System_frequency_response_model_with_underfrequency_load_shedding_protection/index.qmd
      - text: Contribute
        menu:
          - text: How to contribute
            href: ./contribute/howTo/index.qmd
          - text: Quarto Basics
            href: ./contribute/quartoBasics/index.qmd
          - text: Interactive Tutorial
            href: ./contribute/interactiveTutorial/index.qmd
          - text: Model template
            href: ./contribute/modelTemplate/index.qmd
          - text: Test case template
            href: ./contribute/testSystemTemplate/index.qmd
      - href: contact/index.qmd
        text: Contact
    tools:
      - icon: github
        href: https://github.com/CRESYM/Colib_Quarto.github.io
  sidebar:
    - title: About
      style: floating
      collapse-level: 2
      contents: about
    - title: Models
      style: floating
      collapse-level: 2
      contents: models
    - title: Test Cases
      style: floating
      collapse-level: 2
      contents: testCases
    - title: Contribute
      style: floating
      collapse-level: 2
      contents:
        - text: How to contribute
          href: ./contribute/howTo/index.qmd
        - text: Quarto Basics
          href: ./contribute/quartoBasics/index.qmd
        - text: Interactive Tutorial
          href: ./contribute/interactiveTutorial/index.qmd
        - text: Model template
          href: ./contribute/modelTemplate/index.qmd
        - text: Test case template
          href: ./contribute/testSystemTemplate/index.qmd
  page-footer:
    left: |
      Copyright © 2023-2025 Authors of Collaborative Open-Source Dynamic Simulation Library. Content licensed under [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/).
    right:
      - text: About
        href: about/index.qmd
      - text: Contact
        href: ./contact.qmd
      - text: Privacy Policy
        href: https://cresym.eu/privacy-policy/
      - text: Terms of Reference
        href: about/terms.qmd
      - icon: github
        href: https://github.com/CRESYM/Colib_Quarto.github.io
    background: light
    border: true
  back-to-top-navigation: true

format:
  html:
    theme:
      - cosmo
    css:
      - /styles/main.css
    toc: true
    grid:
      body-width: 1200px
    csl: _bibliography/diabetologia.csl

execute:
  freeze: auto

