project:
  type: website

website:
  navbar:
    search: false
    logo: assets/img/Logo_colib.svg
    left:
      - href: index.qmd
        text: Overview
      - about.qmd
      - models.qmd
      - test_cases.qmd
      - templates.qmd
      - contact.qmd
  page-footer:
    left: |
      Copyright © 2023-2025 Authors of Collaborative Open-Source Dynamic Simulation Library.  
      Content licensed under [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/).
    right: |
      [About](about.qmd) • [Contact](contact.qmd) • [Models](models.qmd) • [Test Cases](test_cases.qmd) • [Templates](templates.qmd) • [Privacy Policy](#) • [Terms of Reference](#)
    background: light
    border: true
  back-to-top-navigation: true

format:
  html:
    theme:
      - cosmo
    css:
      - styles.css
    toc: true
    grid:
      body-width: 1200px
