---
title: "Colib"
---

# Explore and Evaluate Dynamic Power System Models and Test Cases using Colib

## An open-source collaborative dynamic simulation library for academia and industry

::: {.button-group}
[Models](models.qmd){.btn-custom} [Test systems](test_cases.qmd){.btn-custom}
:::

## About Colib

The power system and energy systems at large experience a **paradigm shift with many novel, various active components connected**. Appraising the behaviour and reactions of such new items is critical for network operators to simulate and anticipate system operation.

Power industries and academic institutions constantly develop their own models, cases and tools, but they **lack of resources to cover the full scope of components, interesting test cases and maintain those over time.**

Both face the need for a **collaborative shared dynamic simulation library that would benefit to all** by its high quality, its up-to-dateness, transparency of model equations, and concrete applications (real test cases).

Hence this Colib workspace contains **power systems components, networks, and small and large test cases for steady-state and dynamic stability studies**.

For each component model and test case, you will find a detailed description and links to open-source implementations. Many other open libraries of dynamic components and test cases exist. We reference some of them here.

::: {.button-group}
[Contribute](contact.qmd){.btn-custom} [Overview](about.qmd){.btn-custom}
:::


